#!/bin/sh

set -e

sudo true

brew install coreutils gnupg2 jq parallel telnet lynx htop
#brew install gcc
brew install mc lynx
#brew install openjdk-8-jdk
#brew install `sudo apt list | grep '^openjdk-[^/]*-jdk/' | grep -v ,now | sort -t - --key 2 -n | tail -1 | awk '{ print $1; }'`
brew install ant maven gradle
brew install gzip zstd brotli bzip2 xz pigz zip unzip
brew install socat

brew install vim
brew unlink vim
brew install macvim

brew install --build-from-source libfaketime

brew install git git-lfs cmake make

brew install imagemagick

# Perl general:
#sudo cpan version Scalar::Util List::Util # already part of perl
sudo cpan File::Slurp IO::String Tie::IxHash ExtUtils::MakeMaker Module::Build Test::Simple Test::Harness MIME::Base64::URLSafe JSON::PP JSON::XS Text::Trim Digest::SHA3 IO::Compress IO::Zlib xml XML::LibXML
sudo cpan IO::Zlib IO::Compress::Zstd

sudo cpan Term::ReadKey String::ShellQuote

# Perl modules 3rd-party:
#sudo cpan HTTP::Proxy
#sudo cpan Compress::Zstd
