#!/bin/sh

set -e

sudo yum -y install coreutils gnupg2 jq libfaketime parallel telnet lynx htop
sudo yum -y install gcc gcc-c++
sudo yum -y install mc lynx
sudo yum -y install `sudo yum list | grep '^java-[0-9]' | sort | tail -1 | awk '{ print $1; }'`
sudo yum -y install java-1.8.0-openjdk
sudo yum -y install ant maven gradle
sudo yum -y install gzip zstd brotli bzip2 xz pigz zip unzip
sudo yum -y install socat
sudo yum -y install ripgrep ctags

sudo yum -y install vim-X11

sudo yum -y install git cmake make

sudo yum -y install ImageMagick

# Perl general:
sudo yum -y install cpan perl-version perl-File-Slurp perl-Scalar-List-Utils perl-IO-String perl-Tie-IxHash perl-IO-Compress-Zlib perl-IO-Zlib perl-libxml-perl perl-XML-LibXML perl-MIME-Base64-URLSafe perl-JSON-PP perl-JSON-XS perl-Text-Trim perl-Digest-SHA3 perl-ExtUtils-MakeMaker perl-Module-Build perl-Test-Simple perl-Test-Harness
sudo yum -y install Perl-IO-Compress-Zstd || true

sudo yum -y install cpan perl-Tie-IxHash perl-XML-LibXML perl-File-Slurp perl-TermReadKey perl-String-ShellQuote perl-version

# Perl modules 3rd-party:
#sudo cpan HTTP::Proxy
#sudo cpan Compress::Zstd
