#!/bin/sh

set -e

if [ $# -ne 1 ] || [ ! -d "$1" ]; then
	echo "Argument must be provided where files for company exist" >&2
	exit 127
fi
DIR="$1"
if ! echo "$DIR" | grep ^/ >/dev/null; then
	echo "Full source path must be provided: $DIR" >&2
	exit 127
fi
if [ ! -f "$DIR/_is_company" ]; then
	echo "Cannot find _is_company in $DIR" >&2
	exit 127
fi
DEST="$HOME"

if [ -d "$DIR/bin" ]; then
	mkdir -p "$DEST/bin"
	for f in "$DIR"/bin/*; do
		ln -sf "$f" "$DEST/bin/"
	done
fi

mkdir -p "$DEST/.config/_company"
for f in "$DIR"/config/*; do
	ln -sf "$f" "$DEST/.config/_company/"
done

for d in `cat $DIR/_shared`; do
	(
		cd "$DEST/.config/"
		if [ ! -d "$DEST/.config/_company/$d" ]; then
			echo "Directory does not exist: $DEST/.config/_company/$d"
			exit 127
		fi
		mkdir -p $d
		for f in `find _user/$d/ -mindepth 1 -maxdepth 1`; do
			ln -sf `echo $d/ | sed 's,[^/]\+/\+,../,g'`$f $d/
		done
	)
done

(
	cd "$DIR"
	for f in `find .`; do
		if [ -L $f ]; then
			ln -sf "`readlink $f`" "$DEST/$f"
		elif [ -d $f ]; then
			mkdir -p "$DEST/$f"
		elif [ -f $f ]; then
			ln -sf "$PWD/$f" "$DEST/$f"
		else
			echo "Cannot process unknown file type: $f" >&2
		fi
	done
)
