#!/bin/sh

set -e

DEST="$HOME"
if [ ! -d "$PWD/global/" ]; then
	echo "Directory global must exist in current directory: $PWD/global" >&2
	exit 127
fi
DIR="$PWD/global"
if [ ! -f "$DIR/_is_global" ]; then
	echo "Cannot find _is_global in $DIR" >&2
	exit 127
fi

mkdir -p "$DEST/bin"
for f in "$DIR"/bin/*; do
	ln -sf "$f" "$DEST/bin/"
done

mkdir -p "$DEST/.config/_global"
for f in "$DIR"/config/*; do
	ln -sf "$f" "$DEST/.config/_global/"
done

for d in `cat $DIR/_shared`; do
	(
		cd "$DEST/.config/"
		if [ ! -d "$DEST/.config/_global/$d" ]; then
			echo "Directory does not exist: $DEST/.config/_global/$d"
			exit 127
		fi
		mkdir -p $d
		for f in `find _global/$d/ -mindepth 1 -maxdepth 1`; do
			ln -sf ../$f $d/
		done
	)
done

(
	cd global/home
	for f in `find .`; do
		if [ -L $f ]; then
			ln -sf "`readlink $f`" "$DEST/$f"
		elif [ -d $f ]; then
			mkdir -p "$DEST/$f"
		elif [ -f $f ]; then
			ln -sf "$PWD/$f" "$DEST/$f"
		else
			echo "Cannot process unknown file type: $f" >&2
		fi
	done
)
